
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="LGPLv3"

[[mods]] #mandatory

modId="would" #mandatory

version = "${version}"

displayName="Would" #mandatory

logoFile="icon.png" #optional

credits="Ordana" #optional

authors="Ordana, Kayla_the_bee" #optional

itemIcon="would:template" #catalogue icon
description='''
I Would, Would you?
'''

[[dependencies.would]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.would]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.would]]
modId="moonlight"
mandatory=true
versionRange="[1.20-2.12.21,]"
ordering="NONE"
side="BOTH"
